//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the vicon_bridge package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __vicon_bridge__TF_DISTORTCONFIG_H__
#define __vicon_bridge__TF_DISTORTCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace vicon_bridge
{
  class tf_distortConfigStatics;

  class tf_distortConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(tf_distortConfig &config, const tf_distortConfig &max, const tf_distortConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const tf_distortConfig &config1, const tf_distortConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, tf_distortConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const tf_distortConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, tf_distortConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const tf_distortConfig &config) const = 0;
      virtual void getValue(const tf_distortConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T tf_distortConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T tf_distortConfig::* field;

      virtual void clamp(tf_distortConfig &config, const tf_distortConfig &max, const tf_distortConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const tf_distortConfig &config1, const tf_distortConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, tf_distortConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const tf_distortConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, tf_distortConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const tf_distortConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const tf_distortConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, tf_distortConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, tf_distortConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<tf_distortConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(tf_distortConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("tf_pub_rate"==(*_i)->name){tf_pub_rate = boost::any_cast<double>(val);}
        if("tf_publish"==(*_i)->name){tf_publish = boost::any_cast<bool>(val);}
        if("tf_ref_frame"==(*_i)->name){tf_ref_frame = boost::any_cast<std::string>(val);}
        if("tf_frame_in"==(*_i)->name){tf_frame_in = boost::any_cast<std::string>(val);}
        if("tf_frame_out"==(*_i)->name){tf_frame_out = boost::any_cast<std::string>(val);}
        if("delay"==(*_i)->name){delay = boost::any_cast<int>(val);}
        if("position_scale"==(*_i)->name){position_scale = boost::any_cast<double>(val);}
        if("noise_type"==(*_i)->name){noise_type = boost::any_cast<std::string>(val);}
        if("sigma_roll_pitch"==(*_i)->name){sigma_roll_pitch = boost::any_cast<double>(val);}
        if("sigma_yaw"==(*_i)->name){sigma_yaw = boost::any_cast<double>(val);}
        if("sigma_xy"==(*_i)->name){sigma_xy = boost::any_cast<double>(val);}
        if("sigma_z"==(*_i)->name){sigma_z = boost::any_cast<double>(val);}
        if("random_walk_k_xy"==(*_i)->name){random_walk_k_xy = boost::any_cast<double>(val);}
        if("random_walk_k_z"==(*_i)->name){random_walk_k_z = boost::any_cast<double>(val);}
        if("random_walk_sigma_xy"==(*_i)->name){random_walk_sigma_xy = boost::any_cast<double>(val);}
        if("random_walk_sigma_z"==(*_i)->name){random_walk_sigma_z = boost::any_cast<double>(val);}
        if("random_walk_tau_xy"==(*_i)->name){random_walk_tau_xy = boost::any_cast<double>(val);}
        if("random_walk_tau_z"==(*_i)->name){random_walk_tau_z = boost::any_cast<double>(val);}
      }
    }

    double tf_pub_rate;
bool tf_publish;
std::string tf_ref_frame;
std::string tf_frame_in;
std::string tf_frame_out;
int delay;
double position_scale;
std::string noise_type;
double sigma_roll_pitch;
double sigma_yaw;
double sigma_xy;
double sigma_z;
double random_walk_k_xy;
double random_walk_k_z;
double random_walk_sigma_xy;
double random_walk_sigma_z;
double random_walk_tau_xy;
double random_walk_tau_z;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double tf_pub_rate;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool tf_publish;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string tf_ref_frame;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string tf_frame_in;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string tf_frame_out;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int delay;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double position_scale;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string noise_type;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sigma_roll_pitch;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sigma_yaw;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sigma_xy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sigma_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double random_walk_k_xy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double random_walk_k_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double random_walk_sigma_xy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double random_walk_sigma_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double random_walk_tau_xy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double random_walk_tau_z;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("tf_distortConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const tf_distortConfig &__max__ = __getMax__();
      const tf_distortConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const tf_distortConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const tf_distortConfig &__getDefault__();
    static const tf_distortConfig &__getMax__();
    static const tf_distortConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const tf_distortConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void tf_distortConfig::ParamDescription<std::string>::clamp(tf_distortConfig &config, const tf_distortConfig &max, const tf_distortConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class tf_distortConfigStatics
  {
    friend class tf_distortConfig;

    tf_distortConfigStatics()
    {
tf_distortConfig::GroupDescription<tf_distortConfig::DEFAULT, tf_distortConfig> Default("Default", "", 0, 0, true, &tf_distortConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tf_pub_rate = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tf_pub_rate = 250.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tf_pub_rate = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("tf_pub_rate", "double", 0, "rate at which tf publishes transforms. ", "", &tf_distortConfig::tf_pub_rate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("tf_pub_rate", "double", 0, "rate at which tf publishes transforms. ", "", &tf_distortConfig::tf_pub_rate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tf_publish = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tf_publish = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tf_publish = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<bool>("tf_publish", "bool", 0, "determine if output will be published.", "", &tf_distortConfig::tf_publish)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<bool>("tf_publish", "bool", 0, "determine if output will be published.", "", &tf_distortConfig::tf_publish)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tf_ref_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tf_ref_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tf_ref_frame = "world";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("tf_ref_frame", "str", 0, "tf reference frame.", "", &tf_distortConfig::tf_ref_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("tf_ref_frame", "str", 0, "tf reference frame.", "", &tf_distortConfig::tf_ref_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tf_frame_in = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tf_frame_in = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tf_frame_in = "in";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("tf_frame_in", "str", 0, "tf input frame.", "", &tf_distortConfig::tf_frame_in)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("tf_frame_in", "str", 0, "tf input frame.", "", &tf_distortConfig::tf_frame_in)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tf_frame_out = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tf_frame_out = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tf_frame_out = "tf_distort/out";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("tf_frame_out", "str", 0, "tf output frame.", "", &tf_distortConfig::tf_frame_out)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("tf_frame_out", "str", 0, "tf output frame.", "", &tf_distortConfig::tf_frame_out)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.delay = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.delay = 1000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.delay = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<int>("delay", "int", 0, "delay [ms]. ", "", &tf_distortConfig::delay)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<int>("delay", "int", 0, "delay [ms]. ", "", &tf_distortConfig::delay)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_scale = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_scale = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_scale = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("position_scale", "double", 0, "scale of the position measurement", "", &tf_distortConfig::position_scale)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("position_scale", "double", 0, "scale of the position measurement", "", &tf_distortConfig::position_scale)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_type = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_type = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_type = "normal";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("noise_type", "str", 0, "noise distribution. Standard deviation in case for normal, max. in case for uniform distribution. ", "{'enum': [{'name': 'NORMAL', 'type': 'str', 'value': 'normal', 'srcline': 11, 'srcfile': '/home/frank/Documents/code/Landing_Robot_Control/vicon_frank2/catkin_ws/src/vicon_bridge/cfg/tf_distort.cfg', 'description': 'normal distributed noise.', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'UNIFORM', 'type': 'str', 'value': 'uniform', 'srcline': 12, 'srcfile': '/home/frank/Documents/code/Landing_Robot_Control/vicon_frank2/catkin_ws/src/vicon_bridge/cfg/tf_distort.cfg', 'description': 'uniform distributed noise.', 'ctype': 'std::string', 'cconsttype': 'const char * const'}], 'enum_description': 'An enum to set the noise distribution.'}", &tf_distortConfig::noise_type)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("noise_type", "str", 0, "noise distribution. Standard deviation in case for normal, max. in case for uniform distribution. ", "{'enum': [{'name': 'NORMAL', 'type': 'str', 'value': 'normal', 'srcline': 11, 'srcfile': '/home/frank/Documents/code/Landing_Robot_Control/vicon_frank2/catkin_ws/src/vicon_bridge/cfg/tf_distort.cfg', 'description': 'normal distributed noise.', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'UNIFORM', 'type': 'str', 'value': 'uniform', 'srcline': 12, 'srcfile': '/home/frank/Documents/code/Landing_Robot_Control/vicon_frank2/catkin_ws/src/vicon_bridge/cfg/tf_distort.cfg', 'description': 'uniform distributed noise.', 'ctype': 'std::string', 'cconsttype': 'const char * const'}], 'enum_description': 'An enum to set the noise distribution.'}", &tf_distortConfig::noise_type)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sigma_roll_pitch = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sigma_roll_pitch = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sigma_roll_pitch = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_roll_pitch", "double", 0, "std dev for roll and pitch [deg]. ", "", &tf_distortConfig::sigma_roll_pitch)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_roll_pitch", "double", 0, "std dev for roll and pitch [deg]. ", "", &tf_distortConfig::sigma_roll_pitch)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sigma_yaw = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sigma_yaw = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sigma_yaw = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_yaw", "double", 0, "std dev for yaw [deg]. ", "", &tf_distortConfig::sigma_yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_yaw", "double", 0, "std dev for yaw [deg]. ", "", &tf_distortConfig::sigma_yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sigma_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sigma_xy = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sigma_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_xy", "double", 0, "std dev for x/y [m]. ", "", &tf_distortConfig::sigma_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_xy", "double", 0, "std dev for x/y [m]. ", "", &tf_distortConfig::sigma_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sigma_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sigma_z = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sigma_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_z", "double", 0, "std dev for z [m]. ", "", &tf_distortConfig::sigma_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_z", "double", 0, "std dev for z [m]. ", "", &tf_distortConfig::sigma_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.random_walk_k_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.random_walk_k_xy = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.random_walk_k_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_k_xy", "double", 0, "gain for random walk disturbance in x/y axis.", "", &tf_distortConfig::random_walk_k_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_k_xy", "double", 0, "gain for random walk disturbance in x/y axis.", "", &tf_distortConfig::random_walk_k_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.random_walk_k_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.random_walk_k_z = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.random_walk_k_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_k_z", "double", 0, "gain for random walk disturbance in z axis.", "", &tf_distortConfig::random_walk_k_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_k_z", "double", 0, "gain for random walk disturbance in z axis.", "", &tf_distortConfig::random_walk_k_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.random_walk_sigma_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.random_walk_sigma_xy = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.random_walk_sigma_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_sigma_xy", "double", 0, "std dev for gauss markov process in x/y axis [m].", "", &tf_distortConfig::random_walk_sigma_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_sigma_xy", "double", 0, "std dev for gauss markov process in x/y axis [m].", "", &tf_distortConfig::random_walk_sigma_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.random_walk_sigma_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.random_walk_sigma_z = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.random_walk_sigma_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_sigma_z", "double", 0, "std dev for gauss markov process in x/y axis [m].", "", &tf_distortConfig::random_walk_sigma_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_sigma_z", "double", 0, "std dev for gauss markov process in x/y axis [m].", "", &tf_distortConfig::random_walk_sigma_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.random_walk_tau_xy = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.random_walk_tau_xy = 3000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.random_walk_tau_xy = 0.001;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_tau_xy", "double", 0, "time constant for gauss markov process in x/y axis [s].", "", &tf_distortConfig::random_walk_tau_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_tau_xy", "double", 0, "time constant for gauss markov process in x/y axis [s].", "", &tf_distortConfig::random_walk_tau_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.random_walk_tau_z = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.random_walk_tau_z = 3000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.random_walk_tau_z = 0.001;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_tau_z", "double", 0, "time constant for gauss markov process in z axis [s].", "", &tf_distortConfig::random_walk_tau_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_tau_z", "double", 0, "time constant for gauss markov process in z axis [s].", "", &tf_distortConfig::random_walk_tau_z)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(tf_distortConfig::AbstractGroupDescriptionConstPtr(new tf_distortConfig::GroupDescription<tf_distortConfig::DEFAULT, tf_distortConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<tf_distortConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<tf_distortConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<tf_distortConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    tf_distortConfig __max__;
    tf_distortConfig __min__;
    tf_distortConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const tf_distortConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static tf_distortConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &tf_distortConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const tf_distortConfig &tf_distortConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const tf_distortConfig &tf_distortConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const tf_distortConfig &tf_distortConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<tf_distortConfig::AbstractParamDescriptionConstPtr> &tf_distortConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<tf_distortConfig::AbstractGroupDescriptionConstPtr> &tf_distortConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const tf_distortConfigStatics *tf_distortConfig::__get_statics__()
  {
    const static tf_distortConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = tf_distortConfigStatics::get_instance();

    return statics;
  }

//#line 11 "/home/frank/Documents/code/Landing_Robot_Control/vicon_frank2/catkin_ws/src/vicon_bridge/cfg/tf_distort.cfg"
      const char * const tf_distort_NORMAL = "normal";
//#line 12 "/home/frank/Documents/code/Landing_Robot_Control/vicon_frank2/catkin_ws/src/vicon_bridge/cfg/tf_distort.cfg"
      const char * const tf_distort_UNIFORM = "uniform";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __TF_DISTORTRECONFIGURATOR_H__
