// Generated by gencpp from file vicon_bridge/viconGrabPose.msg
// DO NOT EDIT!


#ifndef VICON_BRIDGE_MESSAGE_VICONGRABPOSE_H
#define VICON_BRIDGE_MESSAGE_VICONGRABPOSE_H

#include <ros/service_traits.h>


#include <vicon_bridge/viconGrabPoseRequest.h>
#include <vicon_bridge/viconGrabPoseResponse.h>


namespace vicon_bridge
{

struct viconGrabPose
{

typedef viconGrabPoseRequest Request;
typedef viconGrabPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct viconGrabPose
} // namespace vicon_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vicon_bridge::viconGrabPose > {
  static const char* value()
  {
    return "396f27028ccc2718b2991cabdc1af144";
  }

  static const char* value(const ::vicon_bridge::viconGrabPose&) { return value(); }
};

template<>
struct DataType< ::vicon_bridge::viconGrabPose > {
  static const char* value()
  {
    return "vicon_bridge/viconGrabPose";
  }

  static const char* value(const ::vicon_bridge::viconGrabPose&) { return value(); }
};


// service_traits::MD5Sum< ::vicon_bridge::viconGrabPoseRequest> should match
// service_traits::MD5Sum< ::vicon_bridge::viconGrabPose >
template<>
struct MD5Sum< ::vicon_bridge::viconGrabPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vicon_bridge::viconGrabPose >::value();
  }
  static const char* value(const ::vicon_bridge::viconGrabPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vicon_bridge::viconGrabPoseRequest> should match
// service_traits::DataType< ::vicon_bridge::viconGrabPose >
template<>
struct DataType< ::vicon_bridge::viconGrabPoseRequest>
{
  static const char* value()
  {
    return DataType< ::vicon_bridge::viconGrabPose >::value();
  }
  static const char* value(const ::vicon_bridge::viconGrabPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vicon_bridge::viconGrabPoseResponse> should match
// service_traits::MD5Sum< ::vicon_bridge::viconGrabPose >
template<>
struct MD5Sum< ::vicon_bridge::viconGrabPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vicon_bridge::viconGrabPose >::value();
  }
  static const char* value(const ::vicon_bridge::viconGrabPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vicon_bridge::viconGrabPoseResponse> should match
// service_traits::DataType< ::vicon_bridge::viconGrabPose >
template<>
struct DataType< ::vicon_bridge::viconGrabPoseResponse>
{
  static const char* value()
  {
    return DataType< ::vicon_bridge::viconGrabPose >::value();
  }
  static const char* value(const ::vicon_bridge::viconGrabPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VICON_BRIDGE_MESSAGE_VICONGRABPOSE_H
