// Generated by gencpp from file vicon_bridge/viconCalibrateSegmentRequest.msg
// DO NOT EDIT!


#ifndef VICON_BRIDGE_MESSAGE_VICONCALIBRATESEGMENTREQUEST_H
#define VICON_BRIDGE_MESSAGE_VICONCALIBRATESEGMENTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vicon_bridge
{
template <class ContainerAllocator>
struct viconCalibrateSegmentRequest_
{
  typedef viconCalibrateSegmentRequest_<ContainerAllocator> Type;

  viconCalibrateSegmentRequest_()
    : subject_name()
    , segment_name()
    , z_offset(0.0)
    , n_measurements(0)  {
    }
  viconCalibrateSegmentRequest_(const ContainerAllocator& _alloc)
    : subject_name(_alloc)
    , segment_name(_alloc)
    , z_offset(0.0)
    , n_measurements(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subject_name_type;
  _subject_name_type subject_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _segment_name_type;
  _segment_name_type segment_name;

   typedef double _z_offset_type;
  _z_offset_type z_offset;

   typedef int32_t _n_measurements_type;
  _n_measurements_type n_measurements;





  typedef boost::shared_ptr< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct viconCalibrateSegmentRequest_

typedef ::vicon_bridge::viconCalibrateSegmentRequest_<std::allocator<void> > viconCalibrateSegmentRequest;

typedef boost::shared_ptr< ::vicon_bridge::viconCalibrateSegmentRequest > viconCalibrateSegmentRequestPtr;
typedef boost::shared_ptr< ::vicon_bridge::viconCalibrateSegmentRequest const> viconCalibrateSegmentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator1> & lhs, const ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator2> & rhs)
{
  return lhs.subject_name == rhs.subject_name &&
    lhs.segment_name == rhs.segment_name &&
    lhs.z_offset == rhs.z_offset &&
    lhs.n_measurements == rhs.n_measurements;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator1> & lhs, const ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vicon_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f57831d02c84e74975c7663933fe42d8";
  }

  static const char* value(const ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf57831d02c84e749ULL;
  static const uint64_t static_value2 = 0x75c7663933fe42d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vicon_bridge/viconCalibrateSegmentRequest";
  }

  static const char* value(const ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string subject_name\n"
"string segment_name\n"
"float64 z_offset\n"
"int32 n_measurements\n"
;
  }

  static const char* value(const ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subject_name);
      stream.next(m.segment_name);
      stream.next(m.z_offset);
      stream.next(m.n_measurements);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct viconCalibrateSegmentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vicon_bridge::viconCalibrateSegmentRequest_<ContainerAllocator>& v)
  {
    s << indent << "subject_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subject_name);
    s << indent << "segment_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.segment_name);
    s << indent << "z_offset: ";
    Printer<double>::stream(s, indent + "  ", v.z_offset);
    s << indent << "n_measurements: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_measurements);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VICON_BRIDGE_MESSAGE_VICONCALIBRATESEGMENTREQUEST_H
